spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webclient  # JDBC URL for connecting to MySQL
    username: root                     # MySQL username
    password: pass@word1                      # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema based on entities

  # Optionally configure connection pool settings
  hikari:
    connection-timeout: 20000  # Timeout for a connection to be established (in ms)
    maximum-pool-size: 5       # Maximum number of connections in the pool
    minimum-idle: 1            # Minimum number of idle connections in the pool

server:
  port: 9099  # Port on which the embedded Tomcat server will run
